# This ServiceAccount provides identity for the flipr application within the chainflip namespace.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flipr
  namespace: chainflip
---
# This Role defines the permissions for listing and getting pods and their logs within the chainflip namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: chainflip
  name: get-pods
rules:
  - apiGroups: [ '' ]
    resources: [ 'pods', 'pods/log' ]
    verbs: [ 'get', 'list' ]
---
# This RoleBinding associates the flipr ServiceAccount with the get-pods Role, granting it the permissions defined in the Role.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flipr
  namespace: chainflip
subjects:
  - kind: ServiceAccount
    name: flipr
    namespace: chainflip
roleRef:
  kind: Role
  name: get-pods
  apiGroup: rbac.authorization.k8s.io
---
# This Deployment specifies how the flipr application should be run in pods within the chainflip namespace.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipr
  namespace: chainflip
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flipr
  template:
    metadata:
      labels:
        app: flipr
    spec:
      serviceAccountName: flipr
      containers:
        - name: flipr
          image: sourcap/flipr:release-1.3.0@sha256:47c54d015e7375fb937b72bbb30e7ae4734cc5a32114134f2801d75db90b25a8
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: 'production'
            - name: BETTERSTACK_API_KEY
              value: 'XXX'
            - name: LOGS_SOURCE_TOKEN
              value: 'XXX'
            - name: CRON_SCHEDULE
              value: '0 */3 * * * *'
            - name: NETWORK
              value: 'mainnet'
            - name: CHAINFLIP_NODE_ADDRESS
              value: 'cFXXX'
            - name: NODE_ENDPOINT_CHAINFLIP
              value: 'http://chainflip.chainflip:9944'
            - name: NODE_ENDPOINT_BITCOIN
              value: 'http://flip:flip@bitcoin.chainflip:8332'
            - name: NODE_ENDPOINT_ETHEREUM
              value: 'http://ethereum.chainflip:8545'
            - name: NODE_ENDPOINT_POLKADOT
              value: 'http://polkadot.chainflip:9944'
            - name: NODE_ENDPOINT_ARBITRUM
              value: 'http://arbitrum.chainflip:8545'
            - name: NODE_ENDPOINT_SOLANA
              value: 'http://solana.chainflip:8899'
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: '0.2'
              memory: 256Mi
            limits:
              cpu: '0.4'
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 5
---
# This Service exposes the flipr application on port 80 and routes traffic to the pods' port 3000.
apiVersion: v1
kind: Service
metadata:
  name: flipr
spec:
  selector:
    app: flipr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
