apiVersion: v1
kind: Namespace
metadata:
  name: flipr
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flipr
  namespace: flipr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: chainflip
  name: get-pods
rules:
  - apiGroups: [ '' ]
    resources: [ 'pods', 'pods/log' ]
    verbs: [ 'get', 'list' ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flipr
  namespace: chainflip
subjects:
  - kind: ServiceAccount
    name: flipr
    namespace: flipr
roleRef:
  kind: Role
  name: get-pods
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipr
  namespace: flipr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flipr
  template:
    metadata:
      labels:
        app: flipr
    spec:
      serviceAccountName: flipr
      containers:
        - name: flipr
          image: sourcap/flipr:release-1.0.0@sha256:xxxx
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: 'production'
            - name: BETTERSTACK_API_KEY
              value: '{BETTERSTACK_API_KEY}'
            - name: LOGS_SOURCE_TOKEN
              value: '{LOGS_SOURCE_TOKEN}'
            - name: CHAINFLIP_NODE_ADDRESS
              value: '{CHAINFLIP_NODE_ADDRESS}'
            - name: NODE_ENDPOINT_CHAINFLIP
              value: '{NODE_ENDPOINT_CHAINFLIP}'
            - name: NODE_ENDPOINT_BITCOIN
              value: '{NODE_ENDPOINT_BITCOIN}'
            - name: NODE_ENDPOINT_ETHEREUM
              value: '{NODE_ENDPOINT_ETHEREUM}'
            - name: NODE_ENDPOINT_POLKADOT
              value: '{NODE_ENDPOINT_POLKADOT}'
          resources:
            limits:
              cpu: '0.2'
              memory: 256Mi
            requests:
              cpu: '0.2'
              memory: 256Mi
